apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbitorrent
  annotations:
    cert-manager.io/cluster-issuer: "prod-issuer"
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/New_qBittorrent_Logo.svg/240px-New_qBittorrent_Logo.svg.png"
    forecastle.stakater.com/appName: "Qbittorrent"
    forecastle.stakater.com/group: "MediaCenter"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - qbittorrent.geekhomeinside.io
      secretName: qbittorrent-ingress-tls
  rules:
    - host: qbittorrent.geekhomeinside.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qbittorrent
                port:
                  number: 10095
