apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argo-cd
  # annotations:
    # argocd.argoproj.io/sync-wave: "-99"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-dns
    name: in-cluster
  project: default
  source:
    path: external-dns
    repoURL: 'git@github.com:guiadco/internal_cluster_k8s.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
