apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argo-cd
  # annotations:
  # argocd.argoproj.io/sync-wave: "-99"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: mediacenter
    name: in-cluster
  project: default
  source:
    path: sonarr
    repoURL: "git@github.com:guiadco/internal_cluster_k8s.git"
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
