apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: default
spec:
  project: default
  sources:
    - repoURL: https://charts.truecharts.org/
      chart: radarr
      targetRevision: 16.1.1
      helm:
        valueFiles:
        - $values/radarr/values.yaml
        releaseName: radarr
    - repoURL: 'git@github.com:guiadco/internal_cluster_k8s.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true