# patch_nfs_details.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: NFS_SERVER
              value: yoda.geekhomeinside.io
            - name: NFS_PATH
              value: /yoda/pvc
      volumes:
        - name: nfs-client-root
          nfs:
            server: yoda.geekhomeinside.io
            path: /yoda/pvc