helmCharts:
  - name: sealed-secrets
    releaseName: sealed-secrets
    version: 2.12.0
    repo: https://bitnami-labs.github.io/sealed-secrets
    namespace: kube-system
    valuesFile: values.yaml
