apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  annotations:
    cert-manager.io/cluster-issuer: "prod-issuer"
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Jelly-banner-light.svg/320px-Jelly-banner-light.svg.png"
    forecastle.stakater.com/appName: "jellyfin"
    forecastle.stakater.com/group: "MediaCenter"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - jellyfin.geekhomeinside.io
      secretName: jellyfin-ingress-tls
  rules:
    - host: jellyfin.geekhomeinside.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin
                port:
                  number: 8096
