apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-cd
resources:
  - namespace.yaml
helmCharts:
  - name: argo-cd
    releaseName: argocd
    namespace: argo-cd
    includeCRDs: true
    repo: https://argoproj.github.io/argo-helm
    version: 5.55.0
    valuesFile: values.yaml

configMapGenerator:
  - name: argo-helm-script
    files:
      - helm.sh=sanitize-helm-pull.sh
