apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-services
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: forecastle
    name: in-cluster
  project: default
  source:
    path: external-services
    repoURL: 'git@github.com:guiadco/internal_cluster_k8s.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
