apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
  name: staging-issuer
spec:
  acme:
    email: guiadco@geekhomeinside.com
    preferredChain: ""
    privateKeySecretRef:
      name: staging-issuer-account-key
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
