helmCharts:
  - name: cert-manager
    includeCRDs: true
    releaseName: cert-manager
    version: v1.16.1
    repo: https://charts.jetstack.io
    namespace: cert-manager
    valuesFile: values.yaml

resources:
  - prod-issuer.yaml
  - staging-issuer.yaml
