---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: cert-manager
  name: staging-issuer
spec:
  acme:
    email: guiadco@geekhomeinside.com
    preferredChain: ""
    privateKeySecretRef:
      name: staging-issuer-account-key
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          route53:
            region: eu-west-1
            accessKeyID: AKIASSEXI2IGJL73ENGS
            secretAccessKeySecretRef:
              name: prod-route53-credentials-secret
              key: aws_secret_access_key
