apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyseerr
  annotations:
    cert-manager.io/cluster-issuer: "prod-issuer"
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/icon: "https://i.imgur.com/ZecgKfm.png"
    forecastle.stakater.com/appName: "jellyseerr"
    forecastle.stakater.com/group: "MediaCenter"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - jellyseerr.geekhomeinside.io
      secretName: jellyseerr-ingress-tls
  rules:
    - host: jellyseerr.geekhomeinside.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyseerr
                port:
                  number: 10241
