apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forecastle
  namespace: default
spec:
  project: default
  sources:
    - repoURL: https://stakater.github.io/stakater-charts
      chart: forecastle
      targetRevision: 1.0.128
      helm:
        valueFiles:
        - $values/forecastle/values.yaml
        releaseName: forecastle
    - repoURL: 'git@github.com:guiadco/internal_cluster_k8s.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: forecastle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true