forecastle:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: v1.0.128
  namespace: forecastle
  image:
    name: stakater/forecastle
    tag: v1.0.128
  deployment:
    replicas: 1
    revisionHistoryLimit: 2
  config:
    namespaceSelector:
      any: true
    headerBackground:
    headerForeground:
    title: "Dashboard"
    instanceName:
    crdEnabled: true
  service:
    annotations: {}
    expose: "false"
  ingress:
    enabled: true
    annotations:
      {
        cert-manager.io/cluster-issuer: prod-issuer,
        kubernetes.io/ingress.class: nginx,
      }
    className: nginx
    hosts:
      - host: forecastle.geekhomeinside.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - forecastle.geekhomeinside.io
        secretName: forecastle-tls
